---


#- name: Configure timezone and locale
#  shell: >
#    - sudo echo "Europe/Madrid" > /etc/timezone
#    - sudo dpkg-reconfigure -f noninteractive tzdata
#    - echo "en_US.UTF-8 UTF-8" | sudo tee /etc/locale.gen
#    - echo 'LANG="en_US.UTF-8"' | sudo tee /etc/default/locale
#    - sudo dpkg-reconfigure --frontend=noninteractive locales
#    - sudo update-locale LANG=en_US.UTF-8

- name: Ensure localisation files for '{{ config_system_locale }}' are available
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: Ensure localisation files for '{{ config_system_language }}' are available
  locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: Get current locale and language configuration
  shell: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'LANGUAGE' from current locale and language configuration
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: Configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  become: yes
  shell: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
  changed_when: locale_lang != config_system_locale or locale_language != config_system_language


- name: swap
  block:
    - name: swap | lineinfile swap
      lineinfile:
        path: "/etc/dphys-swapfile"
        regexp: 'CONF_SWAPSIZE=\\d+'
        line: "CONF_SWAPSIZE=2048"

    - name: dphys-swapfile setup
      shell: dphys-swapfile setup
      register: _swapfile_setup

    - name: dphys-swapfile swapon
      shell: dphys-swapfile swapon
      when:
        - _swapfile_setup.stdout | regex_search('generating swapfile', multiline=True, ignorecase=True)
