---
# https://forums.raspberrypi.com/viewtopic.php?t=21632
# 1|0 -> 1=false/off 0=true/on

- name: Disable raspi-config
  shell: "raspi-config nonint {{ item }} 1"
  loop:
    - do_camera
    - do_overscan
    - do_vnc
    - do_overscan
    - do_spi
    - do_i2c
    - do_serial
    - do_onewire
    - do_overclock

- name: Set raspi-config
  shell: "raspi-config nonint {{ item.key }} {{ item.value }}"
  loop:
    -  {key: do_hostname, value: raspi}
    -  {key: do_rgpio, value: 0}
    -  {key: do_wifi_country, value: ES}

- name: get_can_expand
  shell: "raspi-config nonint get_can_expand"
  register: _get_can_expand

- name: set raspi-config get_can_expand
  shell: "raspi-config nonint do_expand_rootfs"
  when: _get_can_expand.stdout == "1"

#define GET_CAN_EXPAND  "sudo raspi-config nonint get_can_expand"
#define EXPAND_FS       "sudo raspi-config nonint do_expand_rootfs"


#define GET_BOOT_WAIT   "sudo raspi-config nonint get_boot_wait"
#define SET_BOOT_WAIT   "sudo raspi-config nonint do_boot_wait %d"
#define GET_SPLASH      "sudo raspi-config nonint get_boot_splash"
#define SET_SPLASH      "sudo raspi-config nonint do_boot_splash %d"
#define GET_PI_TYPE     "sudo raspi-config nonint get_pi_type"